services:
  db:
    # hostname: db
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    # volumes:
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web_server:
    depends_on:
      - db
    build: ./src
    command: python db/setup.py
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PYTHONPATH=/src
    expose:
      - 8000
    links:
      - db